#Ubuntu with a desktop and VNC server.  Will allow us to use gui monitor tools that these libaries have such as tensorboard
FROM consol/ubuntu-xfce-vnc

#switches default user to root
USER 0

#use bash for the shell
SHELL [ "/bin/bash","-c" ]

#Used for GPU setup
# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility


