FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y xauth 
RUN apt-get install -y curl
RUN apt-get update
RUN apt-get install -y gimp
#run this command inside the container get MIT-Magic-Cookie key from xauth list
#RUN xauth add :1 MIT-MAGIC-COOKIE-1 2fef02a020bda4a56b827fe0b8d18635