version: '3'
services:
  novnc:  
    build: .
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    volumes:
    #part before : is on host machine part after the : is on container 
      - /home/shaun/Code/Local_Storage/Ros:/home/local_storage
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
