version: '3'
services:

  novnc:  
    build: .
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8080:8080"
    networks:
      - x11
    volumes:
    #part before : is on host machine part after the : is on container 
      - /home/shaun/Code/Local_Storage/PythonDocker:/home/local_storage
networks:
  x11:
